environment = "dev"
region      = "us-east-1"
tf_state_bucket = "my-terraform-state-bckt43"
log_group_tag_name    = "dev-DockerAPI"
ssm_param_name              = "/cloudwatch/docker-config"
docker_log_group_name       = "/dev/docker/api"
ssm_tag_name                = "docker-cloudwatch-config"
tf_state_region  = "us-east-1"
