environment = "prod"
region      = "eu-west-1"
tf_state_bucket = "my-terraform-state-bckt4321"
log_group_tag_name    = "prod-DockerAPI"
ssm_param_name              = "/prod-cloudwatch/docker-config"
docker_log_group_name       = "/prod/docker/api"
ssm_tag_name                = "prod-docker-cloudwatch-config"
tf_state_region  = "us-east-1"
