name: Destroy Terraform Lambda Infrastructure

on:
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to destroy (dev/staging/prod)'
        required: true
        default: 'dev'

jobs:
  destroy-infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}

    env:
      AWS_REGION: eu-west-1
      ENV: ${{ github.event.inputs.ENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: feature/btl-52

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Destroy REST API Infra
        working-directory: ./infra/api
        run: |
          terraform init
          terraform destroy -auto-approve -var-file=${{ env.ENV }}.tfvars

      - name: Create dummy backend-api.zip for Lambda
        working-directory: ./infra/lambda-idlms
        run: |
          echo "dummy" > dummy.txt
          zip backend-api.zip dummy.txt

      - name: Destroy Lambda Infra
        working-directory: ./infra/lambda-idlms
        run: |
          terraform init
          terraform destroy -auto-approve -var-file=${{ env.ENV }}.tfvars
          
      - name: Destroy SSM 
        working-directory: ./infra/ssm
        run: |
          terraform init
          terraform destroy -auto-approve -var-file=${{ env.ENV }}.tfvars

      - name: Destroy VPC 
        working-directory: ./infra/vpc
        run: |
          terraform init
          terraform destroy -auto-approve -var-file=${{ env.ENV }}.tfvars
